// Game exports
export { default as ArcheryGame } from './games/ArcheryGame/ArcheryGame'
export { default as BaghChalGame } from './games/BaghChalGame/BaghChalGame'
export { default as BrickBreaker } from './games/BrickBreaker/BrickBreaker'
export { default as DoodleJump } from './games/DoodleJump/DoodleJump'
export { default as FlappyBird } from './games/FlappyBird/FlappyBird'
export { default as FroggerGame } from './games/FroggerGame/FroggerGame'
export { default as GoGame } from './games/GoGame/GoGame'
export { default as Home } from '../pages/Home/Home'
export { default as Minesweeper } from './games/Minesweeper/Minesweeper'
export { default as Ludo } from './games/Ludo/Ludo'
export { default as PacMan } from './games/PacMan/PacMan'
export { default as PongGame } from './games/PongGame/PongGame'
export { default as SnakeGame } from './games/SnakeGame/SnakeGame'
export { default as SpaceInvaders } from './games/SpaceInvaders/SpaceInvaders'
export { default as Tetris } from './games/Tetris/Tetris'
export { default as TicTacToe } from './games/TicTacToe/TicTacToe'
